src/MentorBundle/Entity/MentorProcess.php
<?php

namespace MentorBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * MentorProcess
 *
 * @ORM\Table(name="mentor_process")
 * @ORM\Entity(repositoryClass="MentorBundle\Repository\MentorProcessRepository")
 */
class MentorProcess
{
    const STATUS_INACTIVE = 0;
    const STATUS_UNREALIZED = 1;
    const STATUS_REALIZED = 2;
    const STATUS_CLOSED = 3;

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var int
     *
     * @ORM\Column(name="id_mentee", type="integer")
     */
    private $idMentee;

    /**
     * @var int
     *
     * @ORM\Column(name="id_mentor", type="integer")
     */
    private $idMentor;

    /**
     * @var int
     *
     * @ORM\Column(name="status", type="integer")
     */
    private $status;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="start_date", type="datetime")
     */
    private $startDate;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="end_date", type="datetime")
     */
    private $endDate;

    /**
     * @var int
     *
     * @ORM\Column(name="sessions", type="integer", options={"default":0})
     */
    private $sessions = 0;

    /**
     * @ORM\Column(name="sessions_planned", type="integer", options={"default":0});
     * @var int
     */
    private $sessionsPlanned = 0;
    
    /**
     * @ORM\Column(name="sessions_realized", type="integer", options={"default":0});
     * @var int
     */
    private $sessionsRealized = 0;
    
    /**
     * @var int
     *
     * @ORM\Column(name="blocked_for_client", type="integer")
     */
    private $blockedForClient;

    /**
     * @var text
     * @ORM\Column(name="close_reason", type="text", nullable=true)
     */
    private $closeReason;

    /**
     * @var int
     *
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\User", inversedBy="closedProcesses",cascade={"persist"})
     * @ORM\JoinColumn(name="id_closing_user", referencedColumnName="id")
     */
    private $closingUser;

    /**
     * @ORM\OneToMany(targetEntity="MentorBundle\Entity\MentorSession", mappedBy="process",cascade={"persist"})
     */
    public $sessionsList;
    
    /**
     * @ORM\OneToMany(targetEntity="MentorBundle\Entity\MentorGoalCard", mappedBy="process",cascade={"persist"})
     */
    public $goalCards;
    

    /**
     * @ORM\OneToMany(targetEntity="MentorBundle\Entity\MentorProcessSummary", mappedBy="process",cascade={"persist"})
     */
    public $summary;
    
    /**
     * @ORM\ManyToOne(targetEntity="MentorBundle\Entity\UserMentor", inversedBy="processes")
     * @ORM\JoinColumn(name="id_mentor", referencedColumnName="id")
     */
    public $mentor;
    /**
     * @ORM\ManyToOne(targetEntity="MentorBundle\Entity\UserMentee", inversedBy="processes")
     * @ORM\JoinColumn(name="id_mentee", referencedColumnName="id")
     */
    public $mentee;
    
    public static $statuses = [
        null => 'process.status.all',
        self::STATUS_INACTIVE => 'process.status.inactive',
        self::STATUS_UNREALIZED => 'process.status.unrealized',
        self::STATUS_REALIZED => 'process.status.realized',
        self::STATUS_CLOSED => 'process.status.closed',
    ];
    
    public $statusesText = [
        null => 'process.status.all',
        self::STATUS_INACTIVE => 'process.status.inactive',
        self::STATUS_UNREALIZED => 'process.status.unrealized',
        self::STATUS_REALIZED => 'process.status.realized',
        self::STATUS_CLOSED => 'process.status.closed',
    ];

	public function __construct() {
        $this->sessionsList = new ArrayCollection();
        $this->goalCards = new ArrayCollection();
        $this->summary = new ArrayCollection();
    }

	/**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set idMentee
     *
     * @param integer $idMentee
     *
     * @return MentorProcess
     */
    public function setIdMentee($idMentee)
    {
        $this->idMentee = $idMentee;

        return $this;
    }

    /**
     * Get idMentee
     *
     * @return int
     */
    public function getIdMentee()
    {
        return $this->idMentee;
    }

    /**
     * Set idMentor
     *
     * @param integer $idMentor
     *
     * @return MentorProcess
     */
    public function setIdMentor($idMentor)
    {
        $this->idMentor = $idMentor;

        return $this;
    }

    /**
     * @return the $sessionsList
     */
    public function getSessionsList() {
        return $this->sessionsList;
    }

	/**
     * @return the $goalCards
     */
    public function getGoalCards() {
        return $this->goalCards;
    }

	/**
     * @param Ambigous <\Doctrine\Common\Collections\ArrayCollection, MentorSession> $sessionsList
     */
    public function setSessionsList($sessionsList) {
        $this->sessionsList = $sessionsList;
    }

	/**
     * @param \Doctrine\Common\Collections\ArrayCollection $goalCards
     */
    public function setGoalCards($goalCards) {
        $this->goalCards = $goalCards;
    }

	/**
     * Get idMentor
     *
     * @return int
     */
    public function getIdMentor()
    {
        return $this->idMentor;
    }

    /**
     * Set status
     *
     * @param integer $status
     *
     * @return MentorProcess
     */
    public function setStatus($status)
    {
        $this->status = $status;

        return $this;
    }

    /**
     * Get status
     *
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Set startDate
     *
     * @param \DateTime $startDate
     *
     * @return MentorProcess
     */
    public function setStartDate($startDate)
    {
        $this->startDate = $startDate;

        return $this;
    }

    /**
     * Get startDate
     *
     * @return \DateTime
     */
    public function getStartDate()
    {
        return $this->startDate;
    }

    /**
     * Set endDate
     *
     * @param \DateTime $endDate
     *
     * @return MentorProcess
     */
    public function setEndDate($endDate)
    {
        $this->endDate = $endDate;

        return $this;
    }

    /**
     * Get endDate
     *
     * @return \DateTime
     */
    public function getEndDate()
    {
        return $this->endDate;
    }

    /**
     * Set sessions
     *
     * @param integer $sessions
     *
     * @return MentorProcess
     */
    public function setSessions($sessions)
    {
        $this->sessions = $sessions;

        return $this;
    }

    /**
     * Get sessions
     *
     * @return int
     */
    public function getSessions()
    {
        return $this->sessions;
    }

    public function getClosingUser()
    {
        return $this->closingUser;
    }

    public function setClosingUser($user)
    {
        $this->closingUser = $user;
    }

    public function setCloseReason($reason)
    {
        $this->closeReason = $reason;
    }

    public function getCloseReason()
    {
        return $this->closeReason;
    }
    
    public function setSessionsRealized($sessions) 
    {
        $this->sessionsRealized = $sessions;
        return $this;
    }
    
    public function getSessionsRealized()
    {
        return $this->sessionsRealized;
    }
    
    public function setSessionsPlanned($sessions)
    {
        $this->sessionsPlanned = $sessions;
        return $this;
    }
    
    public function getSessionsPlanned()
    {
        return $this->sessionsPlanned;
    }
    
    public function getSessionsLeft()
    {
        return $this->sessions - $this->sessionsRealized;
    }
    
    public function getSessionsLeftToPlanned() 
    {
        return $this->sessions - $this->sessionsPlanned;
    }

    public function isClosed() {
        return $this->status == self::STATUS_CLOSED;
    }

    /**
     * Set blockedForClient
     *
     * @param integer $blockedForClient
     *
     * @return MentorProcess
     */
    public function setBlockedForClient($blockedForClient)
    {
        $this->blockedForClient = $blockedForClient;

        return $this;
    }

    /**
     * Get blockedForClient
     *
     * @return int
     */
    public function getBlockedForClient()
    {
        return $this->blockedForClient;
    }

    public function getStatusText() {
        return $this->statusesText[$this->status];
    }

    public static function getAllStatuses() {
        return array_flip(self::$statuses);
    }

    /**
     * @return the $summary
     */
    public function getSummary() {
        return $this->summary;
    }

    /**
     * @param \Doctrine\Common\Collections\ArrayCollection $summary
     */
    public function setSummary($summary) {
        $this->summary = $summary;
    }

    /**
     * @return the $mentor
     */
    public function getMentor() {
        return $this->mentor;
    }

    /**
     * @return the $mentee
     */
    public function getMentee() {
        return $this->mentee;
    }

    /**
     * @param field_type $mentor
     */
    public function setMentor($mentor) {
        $this->mentor = $mentor;
    }

    /**
     * @param field_type $mentee
     */
    public function setMentee($mentee) {
        $this->mentee = $mentee;
    }
    
    public function addSession(MentorSession $session)
    {
        if ($this->sessionsList->contains($session)) {
            return;
        }
        $this->sessionsList[] = $session;
        $session->setProcess($this);
    }
    
    public function removeSession(MentorSession $session)
    {
        if (!$this->sessionsList->contains($session)) {
            return;
        }
        $this->sessionsList->removeElement($session);
        $session->setProcess(null);
    }
    
    public function addGoalCard(MentorGoalCard $goalCard)
    {
        if ($this->goalCards->contains($goalCard)) {
            return;
        }

src/MentorBundle/Entity/UserClient.php
<?php

namespace MentorBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use PUGX\MultiUserBundle\Validator\Constraints\UniqueEntity;
use AppBundle\Entity\User;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @ORM\Entity
 * @ORM\HasLifecycleCallbacks()
 * @ORM\Table(name="user_client")
 * @UniqueEntity(fields = "username", targetClass = "AppBundle\Entity\User", message="fos_user.username.already_used")
 * @UniqueEntity(fields = "email", targetClass = "AppBundle\Entity\User", message="fos_user.email.already_used")
 */
class UserClient extends User
{
    protected $entityType = 'user_client';
    protected $redirectPath = 'list_clients';
    
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;
    

    /**
     * @Assert\Regex(
     *     pattern="/^[0-9]\d*$/",
     *     htmlPattern = "^[0-9]\d*$",
     *     match=true,
     *     message="Please insert only numbers"
     * )
     * @ORM\Column(type="integer", nullable=true, options={"default":0})
     */
    public $hoursLimit;
    
    /**
     * @Assert\Regex(
     *     pattern="/^[0-9]\d*$/",
     *     htmlPattern = "^[0-9]\d*$",
     *     match=true,
     *     message="Please insert only numbers"
     * )
     * @ORM\Column(type="integer", nullable=true, options={"default":0})
     */
    public $menteeLimit;
    
    /**
    * @ORM\Column(type="string", length=40, nullable=true)
    */
    public $personFunction;
    
    /**
     * @ORM\ManyToOne(targetEntity="MentorBundle\Entity\Company", inversedBy="clients")
     * @ORM\JoinColumn(name="company_id", referencedColumnName="id")
     */
    public $company; 
    
    /**
     * @ORM\OneToMany(targetEntity="MentorBundle\Entity\UserMentee", mappedBy="client")
     */
    public $mentees;
    
    public function __construct() {
        parent::__construct();
        $this->mentees = new ArrayCollection();
        $this->menteeWatchers = new ArrayCollection();
    }
    
    public function getCompany()
    {
        return $this->company;
    }
    
    public function getHoursLimit()
    {
        return $this->hoursLimit;
    }
    
    public function getMenteeLimit()
    {
        return $this->menteeLimit;
    }
    
    public function getPersonFunction()
    {
        return $this->personFunction;
    }
    
    public function getCompanyName() {
        if (empty($this->getCompany())) {
            return '';
        }
        return $this->getCompany()->getCompanyName();
    }

    /**
     * @return Collection
     */
    public function getMentees() {
        return $this->mentees;
    }
    
    /**
     * @ORM\PrePersist
     */
    public function setCreatedAtValue()
    {
        $this->addRole('ROLE_CLIENT');
    }
}

src/MentorBundle/Resources/views/Admin/list_processes.html.twig
{% extends 'AvanzuAdminThemeBundle:layout:default-layout.html.twig' %}
{% form_theme form with ['MentorBundle:forms:form_layouts.html.twig', 'bootstrap_3_horizontal_layout.html.twig'] %}

{% block avanzu_page_content %}
<div class="row">
  <div class="col-md-12">
    <div class="box box-info  collapsed-box">
    <form method="get" action="." class="form-horizontal">
    <div class="box-header with-border">
      <i class="fa fa-search"></i> <h3 class="box-title">{{ 'form.filter.title'|trans }}</h3>
      <div class="box-tools pull-right">
        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"></i></button>
      </div>
    </div>
    <div class="box-body">
    {% for subform in form.mentee %}
      {{ form_widget(subform) }}
    {% endfor %}
    {% for subform in form.mentor %}
      {{ form_widget(subform) }}
    {% endfor %}
    {% if form.company is defined %}
      {% for subform in form.company %}
        {{ form_widget(subform) }}
      {% endfor %}
    {% endif %}
    {{ form_rest(form) }}
    </div>
    <div class="box-footer">
      <div class="pull-right">
        <button class="btn btn-info pull-right" type="submit" >{{ 'search.mentor.submit'|trans }}</button>
      </div>
    </div>
</form>
</div>
<div class="row">
        <div class="col-xs-12">
          <div class="box">
            <div class="box-header">
              <h3 class="box-title">{{ 'mentor.mine.processes'|trans }}</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body table-responsive no-padding">
              <table class="table table-hover">
                <tbody><tr>
                  <th>{{ knp_pagination_sortable(pagination, 'Id', 'e.id') }}
                  {% if pagination.isSorted('e.id') %}<i class="fa fa-sort-alpha-{{ pagination.direction }}"></i>{% endif %}
                  </th>                  
                  <th>{{ 'Mentee'|trans }}</th>
                  <th>{{ 'Mentor'|trans }}</th>
                  {# 
                  <th>{{ knp_pagination_sortable(pagination, 'Mentor'|trans, 'e.mentor.surname') }}
                  {% if pagination.isSorted('e.surname') %}<i class="fa fa-sort-alpha-{{ pagination.direction }}"></i>{% endif %}</th>
                  #}
                  <th>{{ knp_pagination_sortable(pagination, 'Status'|trans, 'e.status') }}
                  {% if pagination.isSorted('e.status') %}<i class="fa fa-sort-alpha-{{ pagination.direction }}"></i>{% endif %}</th>
                  <th>{{ knp_pagination_sortable(pagination, 'Start Date'|trans, 'e.startDate') }}
                  {% if pagination.isSorted('e.startDate') %}<i class="fa fa-sort-alpha-{{ pagination.direction }}"></i>{% endif %}</th>
                  <th>{{ knp_pagination_sortable(pagination, 'End Date'|trans, 'e.endDate') }}
                  {% if pagination.isSorted('e.endDate') %}<i class="fa fa-sort-alpha-{{ pagination.direction }}"></i>{% endif %}</th>
                  <th>{{ knp_pagination_sortable(pagination, 'Sessions'|trans, 'e.sessions') }}
                  {% if pagination.isSorted('e.sessions') %}<i class="fa fa-sort-alpha-{{ pagination.direction }}"></i>{% endif %}</th>
                  <th>{{ knp_pagination_sortable(pagination, 'Sessions realized'|trans, 'e.sessionsRealized') }}
                  {% if pagination.isSorted('e.sessionsRealized') %}<i class="fa fa-sort-alpha-{{ pagination.direction }}"></i>{% endif %}</th>
                  <th>{{ 'Sessions planned'|trans }}</th>
                  <th>{{ 'Sessions left'|trans }}</th>
                  <th style="width: 100px">{{ 'Actions'|trans }}</th>
                </tr>
               {% set sessionsTotal = 0 %}
               {% set sessionsRealizedTotal = 0 %}
               {% set sessionsPlannedTotal = 0 %}
               {% set sessionsLeftTotal = 0 %}
              {% for process in pagination %}
               {% set sessionsTotal = sessionsTotal + process.sessions %}
               {% set sessionsRealizedTotal = sessionsRealizedTotal + process.sessionsRealized %}
               {% set sessionsPlannedTotal = sessionsPlannedTotal + process.sessionsPlanned %}
               {% set sessionsLeftTotal = sessionsLeftTotal + process.sessionsLeft %}
                <tr>
                  <td>{{ process.id }}</td>
                  <td>{{ process.mentee.fullName }}</td>
                  <td>{{ process.mentor.fullName }}</td>
                  <td>{{ process.statusText|trans }}</td>
                  <td>{{ process.startDate|date('Y-m-d H:i:s') }}</td>
                  <td>{{ process.endDate|date('Y-m-d H:i:s') }}</td>
                  <td>{{ process.sessions }}</td>
                  <td>{{ process.sessionsRealized }}</td>
                  <td>{{ process.sessionsPlanned }}</td>
                  <td>{{ process.sessionsLeft }}</td>
                  <td>
                  <div class="btn-group">
                  	<a href="{{ path('process_show', {'id': process.id }) }}" class="btn btn-default" title="{{ 'list.process.show'|trans }}"><i class="fa fa-eye"></i></a>
	                <a href="{{ path('process_pdf', {'id': process.id }) }}" class="btn btn-default" title="{{ 'list.process.pdf'|trans }}"><i class="fa fa-file-pdf-o"></i></a>
	                </div>
                  </td>
                </tr>
                {% endfor %}
                <tfoot>
                <tr>
                <th colspan="6" style="text-align: right;">{{ 'table.rows.total'|trans }}:</th>
                <th>{{ sessionsTotal }}</th>
                <th>{{ sessionsRealizedTotal }}</th>
                <th>{{ sessionsPlannedTotal }}</th>
                <th>{{ sessionsLeftTotal }}</th>
                <td></td>
                </tr>
                </tfoot>

              </tbody></table>
            </div>
            <!-- /.box-body -->
            <div class="box-footer">
                {{ knp_pagination_render(pagination) }}
                <a class="btn btn-info pull-right btn-sm" href="{{ path('adm_pdf_process_list') }}{% if printQueryString %}?{{ printQueryString }}{% endif %}">{{ 'list.process.pdf'|trans }}</a>
            </div>
          </div>
          <!-- /.box -->
        </div>
      </div>
{% endblock %}

{% block avanzu_head %}
<link rel="stylesheet" href="{{ asset('theme/plugins/datepicker/datepicker3.css') }}">
{% endblock %}

{% block avanzu_javascripts_inline%}
<script src="{{ asset('theme/plugins/datepicker/bootstrap-datepicker.js') }}"></script>

<script>
$.fn.datepicker.dates['pl'] = {
                days: ["Niedziela", "Poniedziałek", "Wtorek", "Środa", "Czwartek", "Piątek", "Sobota", "Niedziela"],
                daysShort: ["Nie", "Pn", "Wt", "Śr", "Czw", "Pt", "So", "Nie"],
                daysMin: ["N", "Pn", "Wt", "Śr", "Cz", "Pt", "So", "N"],
                months: ["Styczeń", "Luty", "Marzec", "Kwiecień", "Maj", "Czerwiec", "Lipiec", "Sierpień", "Wrzesień", "Październik", "Listopad", "Grudzień"],
                monthsShort: ["Sty", "Lu", "Mar", "Kw", "Maj", "Cze", "Lip", "Sie", "Wrz", "Pa", "Lis", "Gru"],
                today: "Dzisiaj",
                clear: "Wyczyść",
                weekStart: 1
        };
$(".js-datepicker").datepicker({
format: 'yyyy-mm-dd',
todayBtn: true,
todayHighlight: true,
clearBtn: true,
language: 'pl'

});
</script>
{% endblock %}

src/MentorBundle/Resources/views/Admin/list_sessions.html.twig
{% extends 'AvanzuAdminThemeBundle:layout:default-layout.html.twig' %}
{% form_theme form with ['MentorBundle:forms:form_layouts.html.twig', 'bootstrap_3_horizontal_layout.html.twig'] %}

{% block avanzu_page_content %}
<div class="row">
  <div class="col-md-12">
    <div class="box box-info  collapsed-box">
    <form method="get" action="." class="form-horizontal">
    <div class="box-header with-border">
      <i class="fa fa-search"></i> <h3 class="box-title">{{ 'form.filter.title'|trans }}</h3>
      <div class="box-tools pull-right">
        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"></i></button>
      </div>
    </div>
    <div class="box-body">
    
    {% for subform in form.mentor %}
      {{ form_widget(subform) }}
    {% endfor %}
    {% for subform in form.mentee %}
      {{ form_widget(subform) }}
    {% endfor %}
    
    {% if form.company is defined %}
    {% for subform in form.company %}
      {{ form_widget(subform) }}
    {% endfor %}
    {% endif %}
    
    {{ form_rest(form) }}
    </div>
    <div class="box-footer">
      <div class="pull-right">
        <button class="btn btn-info pull-right" type="submit" >{{ 'search.mentor.submit'|trans }}</button>
      </div>
    </div>
</form>
</div>
<div class="row">
        <div class="col-xs-12">
          <div class="box">
            <div class="box-header">
              <h3 class="box-title">{{ 'mentor.mine.sessions'|trans }}</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body table-responsive no-padding">
              <table class="table table-hover">
                <tbody><tr>
                  <th>{{ knp_pagination_sortable(pagination, 'Id', 'e.id') }}
                  {% if pagination.isSorted('e.id') %}<i class="fa fa-sort-alpha-{{ pagination.direction }}"></i>{% endif %}
                  </th>                  
                  <th>{{ 'Mentee'|trans }}</th>
                      {% if form.company is defined %}
                  <th>{{ 'Company'|trans }} </th>
                  {% endif %}
                  <th>{{ 'Mentor'|trans }}</th>
                  <th>{{ knp_pagination_sortable(pagination, 'Status'|trans, 'e.status') }}
                  {% if pagination.isSorted('e.status') %}<i class="fa fa-sort-alpha-{{ pagination.direction }}"></i>{% endif %}</th>
                  <th>{{ knp_pagination_sortable(pagination, 'Start Date'|trans, 'e.startDate') }}
                  {% if pagination.isSorted('e.startDate') %}<i class="fa fa-sort-alpha-{{ pagination.direction }}"></i>{% endif %}</th>
                  <th>{{ knp_pagination_sortable(pagination, 'End Date'|trans, 'e.endDate') }}
                  {% if pagination.isSorted('e.endDate') %}<i class="fa fa-sort-alpha-{{ pagination.direction }}"></i>{% endif %}</th>
                </tr>
               {% for session in pagination %}
                <tr>
                  <td>{{ session.id }}</td>
                  <td>{{ session.process.mentee.fullName }}</td>
                  {% if form.company is defined %}
                  <td>{{ session.process.mentee.company.companyName }}</td>
                  {% endif %}
                  <td>{{ session.process.mentor.fullName }}</td>
                  <td>{{ session.statusText|trans }}</td>
                  <td>{{ session.startDate|date('Y-m-d H:i:s') }}</td>
                  <td>{{ session.endDate|date('Y-m-d H:i:s') }}</td>
                </tr>
                {% endfor %} 
              </tbody></table>
            </div>
            <!-- /.box-body -->
            <div class="box-footer">
                {{ knp_pagination_render(pagination) }}
            </div>
          </div>
          <!-- /.box -->
        </div>
      </div>
{% endblock %}

{% block avanzu_head %}
<link rel="stylesheet" href="{{ asset('theme/plugins/datepicker/datepicker3.css') }}">
{% endblock %}

{% block avanzu_javascripts_inline%}
<script src="{{ asset('theme/plugins/datepicker/bootstrap-datepicker.js') }}"></script>

<script>
$.fn.datepicker.dates['pl'] = {
                days: ["Niedziela", "Poniedziałek", "Wtorek", "Środa", "Czwartek", "Piątek", "Sobota", "Niedziela"],
                daysShort: ["Nie", "Pn", "Wt", "Śr", "Czw", "Pt", "So", "Nie"],
                daysMin: ["N", "Pn", "Wt", "Śr", "Cz", "Pt", "So", "N"],
                months: ["Styczeń", "Luty", "Marzec", "Kwiecień", "Maj", "Czerwiec", "Lipiec", "Sierpień", "Wrzesień", "Październik", "Listopad", "Grudzień"],
                monthsShort: ["Sty", "Lu", "Mar", "Kw", "Maj", "Cze", "Lip", "Sie", "Wrz", "Pa", "Lis", "Gru"],
                today: "Dzisiaj",
                clear: "Wyczyść",
                weekStart: 1
        };
$(".js-datepicker").datepicker({
format: 'yyyy-mm-dd',
todayBtn: true,
todayHighlight: true,
clearBtn: true,
language: 'pl'

});
</script>
{% endblock %}